-- Customer Analytics para IBM i (Db2 for i)
-- Fuente: GLEARN211/VENTASPF
-- Destino: GLEARN211/SALESTRANS
-- CREATE TABLE GLEARN211/SALESTRANS

CREATE TABLE GLEARN211.SALESTRANS (
    ORDER_ID   VARCHAR(36) NOT NULL,
    FIRST_NAME VARCHAR(30),
    LAST_NAME  VARCHAR(30),
    PROD_CODE  VARCHAR(10),
    PRODUCT    VARCHAR(30) NOT NULL,
    QTY        DECIMAL(5,0) NOT NULL,
    COST_UNIT  DECIMAL(11,2) NOT NULL,
    PRICE_UNIT DECIMAL(11,2) NOT NULL,
    TOTAL_COST DECIMAL(13,2) NOT NULL,
    TOTAL_REV  DECIMAL(13,2) NOT NULL,
    COUNTRY    VARCHAR(30),
    SALES_ZONE VARCHAR(10),
    ORDER_DATE DATE NOT NULL,
    CUST_EMAIL VARCHAR(100) NOT NULL,
    CITY       VARCHAR(40),
    PTYP_CODE  VARCHAR(5),
    PTYP_DESC  VARCHAR(50),
    PRIMARY KEY (ORDER_ID)
);

INSERT INTO GLEARN211.SALESTRANS (
    ORDER_ID, FIRST_NAME, LAST_NAME, PROD_CODE, PRODUCT, QTY,
    COST_UNIT, PRICE_UNIT, TOTAL_COST, TOTAL_REV, COUNTRY,
    SALES_ZONE, ORDER_DATE, CUST_EMAIL, CITY, PTYP_CODE, PTYP_DESC
)
SELECT
    TRIM(ORDERID),
    TRIM(FIRSTNAME),
    TRIM(LASTNAME),
    TRIM(PRODCODE),
    TRIM(PRODUCT),
    QTY,
    COSTUNIT,
    PRICEUNIT,
    TOTALCOST,
    TOTALREV,
    TRIM(COUNTRY),
    TRIM(SALESZONE),
    ORDERDATE,
    LOWER(TRIM(CUSTEMAIL)),
    TRIM(CITY),
    TRIM(PTYPCODE),
    TRIM(PTYPDESC)
FROM GLEARN211.VENTASPF;
